config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees, controllers: {
                           sessions: 'employees/sessions',
                           passwords: 'employees/passwords',
                           registrations: 'employees/registrations',
                           unlocks: 'employees/unlocks',
                           confirmations: 'employees/confirmations',
                           invitations: 'employees/invitations'
                       }

  as :employee do
    get 'login', to: 'devise/sessions#new', as: :user_login
    delete 'logout', to: 'devise/sessions#destroy', as: :user_logout
    get 'registration', to: 'devise/registrations#new', as: :company_registration
  end


  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/activities/:type', to: 'activities#changes'
      delete '/activities/remove', to: 'activities#remove'
      post '/activities/offline_changes', to: 'activities#offline_changes'
      resources :employees, only: [:index, :show]
      resources :departments, only: [:index]
      resources :members, only: [:index]
      namespace :pos do
        resources :suppliers, only: [:index]
        resources :customers, only: [:index]
        resources :products
      end
    end
  end


  post '/submit_contact', to: 'home#submit_contact', as: :submit_contact

  get '/terms-and-conditions', to: 'home#terms_and_conditions'
  get '/pricing', to: 'home#pricing'
  get '/take-a-tour', to: 'home#take_a_tour'
  get '/contact-us', to: 'home#contact_us', as: :contact_us
  get 'modules/employee', to: 'home#employee'
  get 'modules/attendance', to: 'home#attendance'
  get 'modules/bank', to: 'home#bank'

  resources :members

  # For employee resources
  resources :employees do
    get :attendances
    get :settings
    post :import, on: :collection
    get :profile
    get :download_templete, on: :collection
    post :add, on: :collection
    put :update_info, on: :member
    get :access_rights, on: :collection
    get :edit_password, on: :member
    patch :update_password, on: :collection
    patch :reset_password, on: :member
    put :activation, on: :member
    get :payroll_categories, on: :member
    get :increments, on: :member
    get :identity_attachment, on: :member
    get :card
  end

  get '/confirm_email', to: 'employees#confimed_email_error'
  resources :access_rights


  resources :departments do
    get :switch, on: :member
    get :all_settings, on: :member
    member do
      scope :settings do
        get :employee
        get :leave
        get :budget
        get :general
        get :attendance
        get :designation
      end
    end
  end

  resources :settings do
    get :confirm, on: :collection
    get :features, on: :collection
    get :billing, on: :collection
    post :payment_method, on: :collection
    post :company_feature, on: :collection
  end

  namespace :attendance do
    get :dashboard
    resources :attendances do
      get :history, on: :collection
      get :report, on: :collection
      get :employee_wise_report, on: :collection
      get :in, on: :collection
      get :out, on: :member
      get :stats, on: :collection
    end
    resources :day_offs do
      post :generate, on: :collection
    end
  end

  resources :designations, except: [:index]

  resources :companies do
    get :profile, on: :collection
    get :employee, on: :collection
    get :departments, on: :collection
  end

  namespace :bank do
    resources :accounts
  end

  namespace :expenses do
    resources :groups
    resources :categories do
      member do
        get :sub_cats
      end
      resources :sub_categories
    end
  end
  resources :expenses

  namespace :pos do

    namespace :customers do
      resources :categories
      resources :invoices do
        collection do
          get :close_invoice
        end
        member do
          get :history
        end
      end
      resources :invoice_items
      resources :payments
    end
    resources :customers do
      collection do
        post :process_invoice
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :suppliers do
      resources :purchases do
        member do
          get :receive
        end
        collection do
          get :history
        end
      end
      resources :purchase_items
      resources :payments
    end
    resources :suppliers do
      collection do
        post :process_purchase
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :products do
      resources :brands
      resources :models
      resources :categories do
        member do
          get :sub_categories
        end
      end
      resources :queue_codes do
        collection do
          get :print_barcode
          get :clear_all
        end
      end
      resources :sub_categories
      resources :price_tags
    end
    resources :products

    resources :stocks do
      collection do
        get :history
      end
    end
  end

  resources :changed_settings, only: [:new, :create, :edit, :update, :destroy]

  # You can have the root of your site routed with "root"
  root 'home#index'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  get '/*other', :to => 'errors#show', :code => 404
end

app/models/pos/supplier.rb
class Pos::Supplier < ActiveRecord::Base
  belongs_to :department
  has_many :purchases, :class_name => 'Pos::Suppliers::Purchase', foreign_key: :supplier_id, dependent: :destroy
  has_many :payments, :class_name => 'Pos::Suppliers::Payment', foreign_key: :supplier_id, dependent: :destroy
  has_many :products, :class_name => 'Pos::Product', foreign_key: :supplier_id, dependent: :destroy

  include PublicActivity::Model
  tracked owner: proc { |controller, model| controller.current_employee },
          recipient: proc { |controller, model| controller.current_department }

  after_initialize :init

  def init
    self.initial_balance ||= 0.0
  end

  def active_invoice
    purchases.where(is_complete: false)
  end

  def total_invoice
    @total_invoice ||= purchases.sum(:total)
  end

  def total_payment
    @total_payment ||= payments.where(status: 'complete').sum(:amount)
  end

  def total_refund
    0.0 # @total_refund ||= self.refunds.map(&:amount).sum
  end

  def total_discount
    0.0 # @total_discount ||= self.discounts.map(&:amount).sum
  end

  def due_balance
    @due_balance ||= total_invoice - total_payment - total_refund - total_discount + (initial_balance || 0)
  end

  def last_payment_date
    payment_date = ''
    payment = payments.where(status: 'complete').last
    payment_date = payment.date.strftime('%d/%m/%Y') if payment.present?
    payment_date
  end

  def last_any_payment_date
    payment_date = ''
    payment = payments.where(status: 'complete').last
    payment_date = payment.date.strftime('%d/%m/%Y') if payment.present?
    payment_date
  end

  def last_payment_amount
    payment_date = ''
    payment = payments.where(status: 'complete').last
    payment_date = payment.date if payment.present?
    if payment_date.present?
      @last_payment_amount = payments.where(status: 'complete',
                                            date: payment_date).sum(:amount)
    else
      @last_payment_amount = 0
    end
    @last_payment_amount
  end
end

app/models/pos/suppliers.rb
module Pos::Suppliers
  def self.table_name_prefix
    'pos_suppliers_'
  end
end

app/controllers/api/v1/pos/suppliers_controller.rb
class Api::V1::Pos::SuppliersController < Api::V1::V1Base
  def index
    department = Department.find(params[:department_id])
    @suppliers = department.suppliers
  end
end

app/controllers/pos/suppliers/payments_controller.rb
class Pos::Suppliers::PaymentsController < InheritedResources::Base
  before_filter :current_ability
  before_action :set_payment, only: [:show, :edit, :update, :delete]

  def index
    @payments = current_department.suppliers_payments
  end

  def show

  end

  def new
    @payment = Pos::Suppliers::Payment.new
  end

  def create
    @payment = current_department.suppliers_payments.build(payment_params)

    if @payment.save
      flash[:notice] = 'Supplier payment saved successfully.'
    else
      flash[:error] = 'Supplier payment saving failed.'
    end

    redirect_to pos_suppliers_payments_path
  end

  def edit

  end

  def update
    if @payment.update(payment_params)
      flash[:notice] = 'Supplier payment info updated successfully.'
    else
      flash[:error] = 'Supplier payment info update failed.'
    end
    redirect_to pos_suppliers_payments_path
  end

  def delete
    if @payment.destroy
      flash[:notice] = 'Supplier payment deleted successfully.'
    else
      flash[:error] = 'Supplier payment deletion failed.'
    end
    redirect_to pos_suppliers_payments_path
  end

  private

  def set_payment
    @payment = Pos::Suppliers::Payment.find(params[:id])
  end

  def payment_params
    params.require(:pos_suppliers_payment).permit!
  end
end

app/controllers/pos/suppliers/purchase_items_controller.rb
class Pos::Suppliers::PurchaseItemsController < InheritedResources::Base

  private

  def purchase_item_params
    params.require(:pos_suppliers_purchase_item).permit!
  end
end

app/controllers/pos/suppliers/purchases_controller.rb
class Pos::Suppliers::PurchasesController < InheritedResources::Base
  before_filter :current_ability
  before_action :set_purchase, only: [:show, :edit, :update, :delete, :receive]

  def index
    @purchases = current_department.suppliers_purchases.order(id: :desc)
  end

  def show
    respond_to do |format|
      format.html {
        @purchase_items = @purchase.items
      }
      format.json {
        render json: @product.to_json
      }
    end
  end

  def new
    @purchase = Pos::Suppliers::Purchase.new
    @suppliers = current_department.suppliers
    @supplier = @suppliers.find_by_id(params[:supplier_id]) if params[:supplier_id]
  end

  def create
    @purchase = current_department.suppliers_purchases.build(purchase_params)

    if @purchase.save
      flash[:notice] = 'Purchase order saved successfully.'
    else
      flash[:error] = 'Purchase order saving failed.'
    end
    redirect_to pos_suppliers_purchases_path
  end

  def edit
    @suppliers = current_department.suppliers
    @supplier = @purchase.supplier
  end

  def receive
    @supplier = @purchase.supplier
  end

  def update
    if @purchase.update(purchase_params)
      @purchase.update_product_price(params[:price_option]) if params[:price_option].present? && ['update_all', 'average'].include?(params[:price_option])
      flash[:notice] = 'Purchase order updated successfully.'
    else
      flash[:error] = 'Purchase order update failed.'
    end
    redirect_to pos_suppliers_purchases_path
  end

  def delete
    if @purchase.destroy
      flash[:notice] = 'Purchase order deleted successfully.'
    else
      flash[:error] = 'Purchase order deletion failed.'
    end
    redirect_to pos_suppliers_purchases_path
  end

  def history
    if params[:purchase_id].present?
      @purchase = Pos::Suppliers::Purchase.find(params[:purchase_id])
    else
      @product = Pos::Product.find(params[:product_id])
      @purchase_items = @product.purchase_items.includes(:purchase).received
    end
  end

  private

  def set_purchase
    @purchase = Pos::Suppliers::Purchase.find(params[:id])
  end

  def purchase_params
    params.require(:pos_suppliers_purchase).permit!
  end
end

app/controllers/pos/suppliers_controller.rb
class Pos::SuppliersController < InheritedResources::Base
  before_filter :current_ability
  before_action :set_supplier, only: [:show, :edit, :update, :delete, :history, :print_voucher]

  def index
    @suppliers = current_department.suppliers
  end

  def show

  end

  def new
    @supplier = Pos::Supplier.new
  end

  def create
    @supplier = current_department.suppliers.build(supplier_params)

    if @supplier.save
      flash[:notice] = 'Supplier saved successfully.'
    else
      flash[:error] = 'Supplier saving failed.'
    end

    redirect_to pos_suppliers_path
  end

  def edit

  end

  def update
    if @supplier.update(supplier_params)
      flash[:notice] = 'Supplier info updated successfully.'
    else
      flash[:error] = 'Supplier info update failed.'
    end
    redirect_to pos_suppliers_path
  end

  def delete
    if @supplier.destroy
      flash[:notice] = 'Supplier deleted successfully.'
    else
      flash[:error] = 'Supplier deletion failed.'
    end
    redirect_to pos_suppliers_path
  end

  def history
  end

  def process_purchase
    payment_method = params['payment_method']
    @response = "<ul class='invoice-payment-message'>"
    payment_method.each do |key, value|
      if value.present?
        purchase = Pos::Suppliers::Purchase.find(key)
        payment = purchase.payments.build(supplier_id: params['supplier_id'])
        if params['invoice_pay'].present? && params['invoice_pay'][key].present?
          payment.amount = purchase.due_amount
        else
          payment.amount = params['invoice_amount'][key]
        end
        if payment.amount && payment.amount > 1
          payment.commission = params['invoice_commission'][key]
          payment.paid_by_id = params['cashier_id']
          payment.paid_to = params['paid_to']
          payment.payment_method = value
          payment.date = Date.parse(params[:received_date]) || Date.today
          if value == 'cheque'
            if params[:payment_type] == 'Group Payment'
              payment.bank_account_id = params['group_bank_account']
              payment.value_date = Date.parse(params['group_value_date'])
              payment.cheque_number = params['group_cheque_number']
              payment.bank_name = params['group_bank_name']
              payment.bank_branch = params['group_bank_branch']
              payment.is_group = true
            else
              payment.bank_account_id = params['bank_account'][key]
              payment.value_date = Date.parse(params['value_date'][key])
              payment.cheque_number = params['cheque_number'][key]
              payment.bank_name = params['bank_name'][key]
              payment.bank_branch = params['bank_branch'][key]
            end

          end
          if payment.save
            if purchase.due_amount <= 1
              purchase.is_complete = true
              purchase.save
            end
            @response << "<li> Payment #{view_context.link_to "##{payment.id}", pos_suppliers_payment_path(payment.id)} for invoice: ##{key} success with amount #{payment.amount} </li>"
          else
            puts error_messages(payment)
            @response << "<li> Payment #{payment.amount} for invoice: ##{key} failed error: <span class='color-red'> #{error_messages(payment)} </span> </li>"
          end
        end
      end
    end

    redirect_to new_pos_suppliers_payment_path(supplier_id: params['supplier_id']), notice: @response << '</ul>'
  end

  def print_voucher
    if params[:payment_id].present?
      @payments = @supplier.payments.where(id: params[:payment_id])
    else
      payment_date = params[:payment_date] || Date.today
      @payments = @supplier.payments.where('date(created_at) = ?', payment_date)
    end
  end

  private

  def set_supplier
    @supplier = Pos::Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:pos_supplier).permit!
  end
end

app/helpers/api/v1/pos/suppliers_helper.rb
module Api::V1::Pos::SuppliersHelper
end

app/helpers/pos/suppliers/payments_helper.rb
module Pos::Suppliers::PaymentsHelper
end

app/helpers/pos/suppliers/purchase_items_helper.rb
module Pos::Suppliers::PurchaseItemsHelper
end

app/helpers/pos/suppliers/purchases_helper.rb
module Pos::Suppliers::PurchasesHelper
  def link_to_add_product(name, form, association, options = {}, purchase = nil)
    new_object = form.object.send(association).klass.new
    id = new_object.object_id
    fields = form.fields_for(association, new_object, child_index: id) do |builder|
      render("#{association.to_s.singularize}_fields#{purchase.present? ? '_edit' : ''}", ff: builder)
    end
    link_to '#', class: "#{options[:klass]}", data: {id: id, fields: fields.gsub('\n', '')} do
      raw "<i class='fa fa-plus-circle'></i> #{name}"
    end
  end

  def received_status(purchase)
    if purchase.is_received
      raw "<label class='label label-success pt5 pr10 pb5 pl10 br5'> Received </label>"
    else
      html = "<label class='label label-warning pt5 pr10 pb5 pl10 br5'> Pending </label>"
      html += "<a href=#{receive_pos_suppliers_purchase_path(purchase)} class='btn btn-success ml5 pt0 pb0 pr8 pl8' title='Receive Order'><i class='fa fa-check-circle'></i></a>"
      # html += "<a href=#{receive_pos_suppliers_purchase_path(purchase)} class='btn btn-danger ml5 pt2 pb2 pr8 pl8' title='Cancel Order'><i class='fa fa-ban'></i></a>"
      raw html
    end
  end
end

app/helpers/pos/suppliers_helper.rb
module Pos::SuppliersHelper
end

app/views/pos/suppliers/purchases/_form.html.erb
<%= form_for @purchase, html: {id: 'supplier-order-form'} do |f| %>
    <div class="clearfix mb5">
      <div class="col-sm-6">
        <div class="row">
          <table style="width: 100%;">
            <tbody>
            <tr>
              <td width="200px">
                <b> Supplier: </b>
              </td>
              <td>
                <%= f.select :supplier_id, options_for_select(@suppliers.collect { |sp| [sp.name, sp.id] }, (@supplier ? @supplier.id : '')), {prompt: "Select Supplier..."}, {class: 'form-control reset-border-radius mb4'} %>
              </td>
            </tr>
            <tr>
              <td>
                <b> Issue Date: </b>
              </td>
              <td>
                <%= f.text_field :issue_date, class: "form-control mb4 reset-border-radius" %>
              </td>
            </tr>
            <tr>
              <td>
                <b> Expected Delivery Date: </b>
              </td>
              <td>
                <%= f.text_field :expected_delivery, class: "form-control reset-border-radius mb4" %>
              </td>
            </tr>
            <%# unless f.object.new_record? %>
                <!--<tr>-->
                  <!--<td>-->
                    <!--<b> Receipt order? </b>-->
                  <!--</td>-->
                  <!--<td>-->
                    <!--<%#= f.check_box :is_received, {checked: true}, true %>-->
                  <!--</td>-->
                <!--</tr>-->
            <%# end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="row">
          <div class="clearfix pl30" style="min-height: 120px;">
            <!--<div class="label label-info text-left" style="display: block;">-->
              <!--<h4 class="mt0 mb0 pt3 pb3"> In case of cost price changes! </h4>-->
            <!--</div>-->

            <!--<div class="price-options" style="visibility: hidden">-->
              <!--<div class="price-option">-->
                <!--<label>-->
                  <!--<%#= radio_button_tag :price_option, 'update_all' %>-->
                  <!--Change all previous product to new price.-->
                <!--</label>-->
              <!--</div>-->
              <!--<div class="price-option">-->
                <!--<label>-->
                  <!--<%#= radio_button_tag :price_option, 'average' %>-->
                  <!--Change all previous product to in average with price.-->
                <!--</label>-->
              <!--</div>-->
              <!--<div class="price-option">-->
                <!--<label>-->
                  <!--<%#= radio_button_tag :price_option, 'manual' %>-->
                  <!--Will generate price tag for all previous items.-->
                <!--</label>-->
              <!--</div>-->
            <!--</div>-->
          </div>
          <%= link_to_add_product 'Add Product', f, :items, {klass: 'btn btn-default add-product-link reset-border-radius pull-right'} %>
        </div>
      </div>
    </div>
    <% if @supplier.present? %>
        <div class="col-md-12 reset-padding">
          <%= render 'products', f: f %>
          <div class="col-md-12 reset-padding mt20">
            <div class="col-md-5 reset-padding">
              <%= f.label :instruction, 'Any Instruction?' %>
              <%= f.text_area :instruction, class: "form-control note-height" %>
            </div>
            <div class="col-md-2"></div>
            <div class="col-md-5 reset-padding">
              <div class="col-md-12 reset-padding">
                <div class="col-md-4 reset-padding">
                  <%= f.label :amount, 'Sub Total' %>
                </div>
                <div class="col-md-8 reset-padding">
                  <%= f.text_field :amount, class: "form-control subtotal reset-border-radius", readonly: 'readonly' %>
                </div>
              </div>

              <!--<div class="col-md-12 reset-padding mt5">-->
                <!--<div class="col-md-4 reset-padding">-->
                  <!--<%#= f.label :vat %>-->
                <!--</div>-->
                <!--<div class="col-md-8 reset-padding">-->
                  <!--<%#= f.text_field :vat, class: "form-control vat reset-border-radius" %>-->
                <!--</div>-->
              <!--</div>-->

              <div class="col-md-12 reset-padding mt5">
                <div class="col-md-4 reset-padding">
                  <%= f.label :total %>
                </div>
                <div class="col-md-8 reset-padding">
                  <%= f.text_field :total, class: "form-control total_price reset-border-radius", readonly: 'readonly' %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="pull-right mt20">
          <%= f.submit class: 'btn btn-primary' %>
        </div>
    <% else %>
        <%= render 'shared/no_data_found', message: "<strong> Info: </strong> Select supplier first to add purchase item!" %>
    <% end %>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#new_pos_suppliers_invoice').syftValidator();
        $('#pos_suppliers_purchase_supplier_id').change(function () {
            window.location.href = '<%= new_pos_suppliers_purchase_path %>?supplier_id=' + $(this).val();
        });
        $('#pos_suppliers_purchase_issue_date, #pos_suppliers_purchase_expected_delivery').datetimepicker({
            format: 'YYYY-MM-DD',
            defaultDate: "<%= Date.today %>"
        });
    });
</script>

app/views/pos/suppliers/purchases/_histories.html.erb
<div class="table-warapper ">
  <div class="table-warapper-body">
    <table class="table tablesorter beaccount-table table-responsive table-hover table-striped attendance-history-modal">
      <thead>
      <tr>
        <th>Supplier</th>
        <th>Received Date</th>
        <th>Received Qty</th>
        <th>Purchased Price</th>
        <th>Purchase Order ID</th>
      </tr>
      </thead>
      <tbody id="staff-attendance">
      <% @purchase_items.each do |item| %>
        <% purchase = item.purchase %>
        <tr>
          <td><%= purchase.supplier.name if purchase.supplier.present? %></td>
          <td><%= format_date(purchase.receive_date) %></td>
          <td><%= item.received_quantity %></td>
          <td><%= item.amount %></td>
          <td><%= link_to "##{purchase.id}", pos_suppliers_purchase_path(purchase) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
    <!--<div id="modal-pager">-->
    <!--<%#= render 'shared/pagination' if @purchase_items.size > 10 %>-->
    <!--</div>-->
    <div class="no-data-found">
      <% unless @purchase_items.present? %>
        <%= render 'shared/no_data_found', message: 'No purchase history found' %>
      <% end %>
    </div>
  </div>
</div>

app/views/pos/suppliers/purchases/index.html.erb
<div class="row reset-padding">
  <div class="content-wrapper" id="rule-content">
    <div class="header-wrapper">
      <h4>
        Purchase Order List
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper" id="provident-fund-rule-content">
      <% if @purchases.present? %>
        <div class="row actions-button">
          <div class="add-more-rule clearfix">
            <%= link_to new_pos_suppliers_purchase_path, class: 'btn btn-default pull-right' do %>
              <i class="fa fa-plus-circle"></i> New Purchase Order
            <% end %>
          </div>
        </div>
        <div class="row content-body">
          <table class="table action-table beaccount-table tablesorter table-responsive table-hover table-striped">
            <thead>
            <tr>
              <th>Order ID</th>
              <th>Location</th>
              <th>Supplier</th>
              <th>Products</th>
              <th>Amount</th>
              <th>Status</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @purchases.each do |purchase| %>
              <tr>
                <td> #<%= purchase.id %> </td>
                <td><%= purchase.department.name %> </td>
                <td><%= purchase.supplier.name if purchase.supplier.present? %> </td>
                <td><%= purchase.items.sum(:issued_quantity) %> </td>
                <td><%= purchase.total %> </td>
                <td>
                  <%= received_status(purchase) %>
                </td>
                <td class="actions">
                  <%= link_to pos_suppliers_purchase_path(purchase), class: 'btn info-color' do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <% unless purchase.is_received %>
                    <%= link_to edit_pos_suppliers_purchase_path(purchase), class: 'btn warning-color' do %>
                      <i class="fa fa-pencil-square-o"></i>
                    <% end %>
                  <% end %>
                  <%= link_to pos_suppliers_purchase_path(purchase), class: 'btn danger-color', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-times"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <div class="text-center table-cell">
          <p>
            Current department don't have any Purchase Order. <%#= link_to 'Learn more', '#', class: 'link' %>
            <!--<i class="fa fa-info-circle btn btn-info reset-border-radius" data-toggle='popover' data-placement='top' title="Provident Fund Account" data-content="Click on the create new one button to create provident fund account then it will show the account  list  "></i>-->
          </p>
          <%= link_to new_pos_suppliers_purchase_path, class: 'btn btn-default reset-border-radius' do %>
            <i class="fa fa-plus-circle"></i> Add new one
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pos/suppliers/purchases/new.js.erb
popupMessage('Please select a product to see its purchase history', 'alert-danger');

app/views/pos/suppliers/purchases/show.html.erb
<div class="row reset-padding">
  <div class="content-wrapper" id="rule-content">
    <div class="header-wrapper">
      <h4>
        Purchase Order: <%= @purchase.code %>
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <% if @purchase.present? %>
        <div class="row content-body">
          <div id="advances">
            <table class="table table-user-information table-striped">
              <tbody>
              <tr>
                <td><label> Order ID </label></td>
                <td>
                  # <%= @purchase.id %>
                </td>
              </tr>
              <tr>
                <td><label> Supplier </label></td>
                <td> <%= @purchase.supplier.name if @purchase.supplier.present? %> </td>
              </tr>
              <tr>
                <td><label> Issue Date </label></td>
                <td> <%= @purchase.issue_date %> </td>
              </tr>
              <tr>
                <td><label> Expected Delivery Date </label></td>
                <td> <%= @purchase.expected_delivery %> </td>
              </tr>

              <% if @purchase.is_received %>
                <tr>
                  <td><label> Order Status </label></td>
                  <td> Received </td>
                </tr>
                <tr>
                  <td><label> Receive Date </label></td>
                  <td> <%= @purchase.receive_date %> </td>
                </tr>
              <% else %>
                <tr>
                  <td><label> Order Status </label></td>
                  <td> Not received yet. </td>
                </tr>
              <% end %>
              <tr>
                <td><label> Order Total </label></td>
                <td><b><%= @purchase.total %></b>  </td>
              </tr>
              </tbody>

            </table>
          </div>

          <div class="">
            <h4>Ordered Items</h4>
            <div class="table-warapper ">
              <div class="table-warapper-body">
                <table class="table tablesorter beaccount-table table-responsive table-hover table-striped attendance-history-modal">
                  <thead>
                  <tr>
                    <th>Product</th>
                    <th>Ordered Qty</th>
                    <% if @purchase.is_received %>
                      <th>Received Qty</th>
                    <% end %>
                    <th>Purchase Price</th>
                    <th>Sale Price</th>
                    <th>Total</th>
                    <th></th>
                  </tr>
                  </thead>
                  <tbody>
                  <% @purchase_items.each do |item| %>
                    <tr>
                      <td><%= item.product.name if item.product.present? %></td>
                      <td><%= item.issued_quantity %></td>
                      <% if @purchase.is_received %>
                        <td><%= item.received_quantity %></td>
                      <% end %>
                      <td><%= item.amount %></td>
                      <td><%= item.sale_price %></td>
                      <td><%= item.total %></td>
                      <td>
                        <%= link_to history_pos_suppliers_purchases_path(product_id: item.product_id), title: 'Product purchase order history', remote: true, class: 'purchase-history-link' do %>
                          <i class="fa fa-pie-chart" aria-hidden="true"></i>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                  </tbody>
                </table>
                <!--<div id="modal-pager">-->
                <!--<%#= render 'shared/pagination' if @purchase_items.size > 10 %>-->
                <!--</div>-->
                <div class="no-data-found">
                  <% unless @purchase_items.present? %>
                    <%= render 'shared/no_data_found', message: 'No items ordered.' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="text-center table-cell">
          <p>
            Sorry record not found :(
          </p>
        </div>
      <% end %>
    </div>
  </div>
</div>