config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees, controllers: {
                           sessions: 'employees/sessions',
                           passwords: 'employees/passwords',
                           registrations: 'employees/registrations',
                           unlocks: 'employees/unlocks',
                           confirmations: 'employees/confirmations',
                           invitations: 'employees/invitations'
                       }

  as :employee do
    get 'login', to: 'devise/sessions#new', as: :user_login
    delete 'logout', to: 'devise/sessions#destroy', as: :user_logout
    get 'registration', to: 'devise/registrations#new', as: :company_registration
  end


  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/activities/:type', to: 'activities#changes'
      delete '/activities/remove', to: 'activities#remove'
      post '/activities/offline_changes', to: 'activities#offline_changes'
      resources :employees, only: [:index, :show]
      resources :departments, only: [:index]
      resources :members, only: [:index]
      namespace :pos do
        resources :suppliers, only: [:index]
        resources :customers, only: [:index]
        resources :products
      end
    end
  end


  post '/submit_contact', to: 'home#submit_contact', as: :submit_contact

  get '/terms-and-conditions', to: 'home#terms_and_conditions'
  get '/pricing', to: 'home#pricing'
  get '/take-a-tour', to: 'home#take_a_tour'
  get '/contact-us', to: 'home#contact_us', as: :contact_us
  get 'modules/employee', to: 'home#employee'
  get 'modules/attendance', to: 'home#attendance'
  get 'modules/bank', to: 'home#bank'

  resources :members

  # For employee resources
  resources :employees do
    get :attendances
    get :settings
    post :import, on: :collection
    get :profile
    get :download_templete, on: :collection
    post :add, on: :collection
    put :update_info, on: :member
    get :access_rights, on: :collection
    get :edit_password, on: :member
    patch :update_password, on: :collection
    patch :reset_password, on: :member
    put :activation, on: :member
    get :payroll_categories, on: :member
    get :increments, on: :member
    get :identity_attachment, on: :member
    get :card
  end

  get '/confirm_email', to: 'employees#confimed_email_error'
  resources :access_rights


  resources :departments do
    get :switch, on: :member
    get :all_settings, on: :member
    member do
      scope :settings do
        get :employee
        get :leave
        get :budget
        get :general
        get :attendance
        get :designation
      end
    end
  end

  resources :settings do
    get :confirm, on: :collection
    get :features, on: :collection
    get :billing, on: :collection
    post :payment_method, on: :collection
    post :company_feature, on: :collection
  end

  namespace :attendance do
    get :dashboard
    resources :attendances do
      get :history, on: :collection
      get :report, on: :collection
      get :employee_wise_report, on: :collection
      get :in, on: :collection
      get :out, on: :member
      get :stats, on: :collection
    end
    resources :day_offs do
      post :generate, on: :collection
    end
  end

  resources :designations, except: [:index]

  resources :companies do
    get :profile, on: :collection
    get :employee, on: :collection
    get :departments, on: :collection
  end

  namespace :bank do
    resources :accounts
  end

  namespace :expenses do
    resources :groups
    resources :categories do
      member do
        get :sub_cats
      end
      resources :sub_categories
    end
  end
  resources :expenses

  namespace :pos do

    namespace :customers do
      resources :categories
      resources :invoices do
        collection do
          get :close_invoice
        end
        member do
          get :history
        end
      end
      resources :invoice_items
      resources :payments
    end
    resources :customers do
      collection do
        post :process_invoice
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :suppliers do
      resources :purchases do
        member do
          get :receive
        end
        collection do
          get :history
        end
      end
      resources :purchase_items
      resources :payments
    end
    resources :suppliers do
      collection do
        post :process_purchase
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :products do
      resources :brands
      resources :models
      resources :categories do
        member do
          get :sub_categories
        end
      end
      resources :queue_codes do
        collection do
          get :print_barcode
          get :clear_all
        end
      end
      resources :sub_categories
      resources :price_tags
    end
    resources :products

    resources :stocks do
      collection do
        get :history
      end
    end
  end

  resources :changed_settings, only: [:new, :create, :edit, :update, :destroy]

  # You can have the root of your site routed with "root"
  root 'home#index'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  get '/*other', :to => 'errors#show', :code => 404
end

app/models/expenses/category.rb
class Expenses::Category < ActiveRecord::Base
  belongs_to :department
  belongs_to :group, class_name: 'Expenses::Group'
  has_many :sub_categories, class_name: 'Expenses::SubCategory', dependent: :destroy
  has_many :expenses, dependent: :destroy

  validates :department_id, :name, presence: true
end

app/models/expenses/group.rb
class Expenses::Group < ActiveRecord::Base
  belongs_to :department
  has_many :categories, class_name: 'Expenses::Category', dependent: :destroy
end

app/models/expenses/sub_category.rb
class Expenses::SubCategory < ActiveRecord::Base
  belongs_to :category, class_name: 'Expenses::Category'
  has_many :expenses, dependent: :destroy
end

app/models/pos/products/sub_category.rb
class Pos::Products::SubCategory < ActiveRecord::Base
  belongs_to :department
  belongs_to :category, :class_name => 'Pos::Products::Category'
  has_many :products, :class_name => 'Pos::Product', foreign_key: :sub_category_id, dependent: :destroy
end

app/controllers/expenses/categories_controller.rb
class Expenses::CategoriesController < ApplicationController
  before_filter :current_ability
  before_action :set_category, only: [:edit, :update, :delete, :sub_cats]

  def index
    @categories = current_department.expenses_categories
  end

  def new
    @category = Expenses::Category.new
    @groups = current_department.expenses_groups
  end

  def create
    @category = current_department.expenses_categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to expenses_categories_path, notice: 'Expense Category saved successfully.' }
      else
        format.html { redirect_to expenses_categories_path, error: 'Expense Category saving failed.' }
      end
      format.js {}
    end
  end

  def edit

  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Expense Category info updated successfully.'
    else
      flash[:error] = 'Expense Category info update failed.'
    end
    redirect_to expenses_categories_path
  end

  def delete
    if @category.destroy
      flash[:notice] = 'Expense Category deleted successfully.'
    else
      flash[:error] = 'Expense Category deletion failed.'
    end
    redirect_to expenses_categories_path
  end

  def sub_cats
    @sub_categories = @category.sub_categories
  end

  private

  def set_category
    @category = Expenses::Category.find(params[:id])
  end

  def category_params
    params.require(:expenses_category).permit!
  end
end

app/controllers/expenses/groups_controller.rb
class Expenses::GroupsController < ApplicationController
  before_filter :current_ability
  before_action :set_group, only: [:edit, :update, :destroy, :categories]

  def index
    @groups = current_department.expenses_groups
  end

  def new
    @group = Expenses::Group.new
  end

  def create
    @group = current_department.expenses_groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to expenses_groups_path, notice: 'Expense Group saved successfully.' }
      else
        format.html { redirect_to expenses_groups_path, danger: errors_to_message_string(@group.errors) }
      end
      format.js {}
    end
  end

  def edit

  end

  def update
    if @group.update(group_params)
      flash[:notice] = 'Expense group info updated successfully.'
    else
      flash[:error] = errors_to_message_string(@group.errors)
    end
    redirect_to expenses_groups_path
  end

  def destroy
    if @group.destroy
      flash[:notice] = 'Group deleted successfully.'
    else
      flash[:danger] = errors_to_message_string(@group.errors)
    end
    redirect_to expenses_groups_path
  end

  def categories
    @categories = @group.categories
  end

  private

  def set_group
    @group = Expenses::Group.find(params[:id])
  end

  def group_params
    params.require(:expenses_group).permit!
  end
end

app/controllers/expenses/sub_categories_controller.rb
class Expenses::SubCategoriesController < ApplicationController
  before_filter :current_ability
  before_action :set_category
  before_action :set_sub_category, only: [:edit, :update, :destroy]

  def index
    @sub_categories = @category.sub_categories
  end

  def new
    @sub_category = @category.sub_categories.build
  end

  def create
    @sub_category = @category.sub_categories.build(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to expenses_category_sub_categories_path(@category), notice: 'Expense Sub-Category saved successfully.' }
      else
        format.html { redirect_to expenses_category_sub_categories_path(@category), error: errors_to_message_string(@sub_category) }
      end
      format.js {}
    end
  end

  def edit
  end

  def update
    if @sub_category.update(sub_category_params)
      flash[:notice] = 'Expense Sub-Category info updated successfully.'
    else
      flash[:error] = 'Expense Sub-Category info update failed.'
    end
    redirect_to expenses_category_sub_categories_path(@category)
  end

  def destroy
    if @sub_category.destroy
      flash[:notice] = 'Expense Sub-Category deleted successfully.'
    else
      flash[:error] = 'Expense Sub-Category deletion failed.'
    end
    redirect_to expenses_category_sub_categories_path(@category)
  end

  private

  def set_category
    @category = Expenses::Category.find(params[:category_id])
  end

  def set_sub_category
    @sub_category = @category.sub_categories.find(params[:id])
  end

  def sub_category_params
    params.require(:expenses_sub_category).permit!
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_filter :current_ability
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  def index
    @expenses = current_department.expenses
  end

  def show
  end

  def new
    @expense = Expense.new
    @categories = current_department.expenses_categories
    @sub_categories = @categories.present? ? @categories.first.sub_categories : []
  end

  def create
    @expense = current_department.expenses.build(expense_params)
    @expense.created_by = current_employee.id
    respond_to do |format|
      if @expense.save
        format.html { redirect_to expenses_path, notice: 'Expense saved successfully.' }
      else
        format.html { redirect_to expenses_path, error: 'Expense saving failed.' }
      end
      format.js {}
    end
  end

  def edit
    @categories = current_department.expenses_categories
    @sub_categories = @expense.category.sub_categories
  end

  def update
    if @expense.update(expense_params)
      flash[:notice] = 'Expense info updated successfully.'
    else
      flash[:error] = 'Expense info update failed.'
    end
    redirect_to expenses_path
  end

  def destroy
    if @expense.destroy
      flash[:notice] = 'Expense deleted successfully.'
    else
      flash[:error] = 'Expense deletion failed.'
    end
    redirect_to expenses_path
  end

  private

  def set_expense
    @expense = Expense.find(params[:id])
  end

  def expense_params
    params.require(:expense).permit!
  end
end

app/controllers/pos/products/sub_categories_controller.rb
class Pos::Products::SubCategoriesController < InheritedResources::Base
  before_filter :current_ability
  before_action :set_sub_category, only: [:edit, :update, :delete]

  def index
    @sub_categories = current_department.products_sub_categories
  end

  def new
    sub_cat_code = "PSC#{current_department.id}000#{current_department.products_categories.count + 1}"
    @sub_category = Pos::Products::SubCategory.new({code: sub_cat_code})
    if params[:category_id].present?
      @category = Pos::Products::Category.find(params[:category_id])
    else
      @categories = current_department.products_categories
    end
  end

  def create
    @sub_category = current_department.products_sub_categories.build(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to pos_products_sub_categories_path, notice: 'Product Sub-Category saved successfully.' }
      else
        format.html { redirect_to pos_products_sub_categories_path, error: 'Product Sub-Category saving failed.' }
      end
      format.js {}
    end
  end

  def edit
    @categories = current_department.products_categories
  end

  def update
    if @sub_category.update(sub_category_params)
      flash[:notice] = 'Product Sub-Category info updated successfully.'
    else
      flash[:error] = 'Product Sub-Category info update failed.'
    end
    redirect_to pos_products_sub_categories_path
  end

  def delete
    if @sub_category.destroy
      flash[:notice] = 'Product Sub-Category deleted successfully.'
    else
      flash[:error] = 'Product Sub-Category deletion failed.'
    end
    redirect_to pos_products_sub_categories_path
  end

  private

  def set_sub_category
    @sub_category = Pos::Products::SubCategory.find(params[:id])
  end

  def sub_category_params
    params.require(:pos_products_sub_category).permit!
  end
end

app/helpers/expenses/categories_helper.rb
module Expenses::CategoriesHelper
end

app/helpers/expenses/groups_helper.rb
module Expenses::GroupsHelper
end

app/helpers/expenses/sub_categories_helper.rb
module Expenses::SubCategoriesHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/pos/products/sub_categories_helper.rb
module Pos::Products::SubCategoriesHelper
end

app/views/expenses/sub_categories/_form.html.erb
<div class="provident-fund-rule-form">
  <%= form_for [@category, @sub_category], url: @sub_category.new_record? ? expenses_category_sub_categories_path(@category, @sub_category) : expenses_category_sub_category_path(@category, @sub_category) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control reset-border-radius', data: {required: true} %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control reset-border-radius' %>
    </div>
    <div class="actions clearfix">
      <%= f.submit class: 'btn btn-default pull-right reset-border-radius' %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
    $(function () {
        $('#new_expenses_sub_category').syftValidator();
    });
</script>

app/views/expenses/sub_categories/_form_modal.html.erb
<%= render 'shared/modal_header', modal_title: 'New Product Sub-Category' %>
<%= form_for([@category, @sub_category], url: expenses_category_sub_categories_path(@category, @sub_category), remote: true) do |f| %>
  <div class="modal-body">
    <div class="form-group">
      <%= f.label :category_id, 'Category: ' %>
      <%= @category.name %>
    </div>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control reset-border-radius', data: {required: true} %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control reset-border-radius' %>
    </div>
  </div>

  <div class="modal-footer">
    <div class="pull-right">
      <%= f.submit class: 'btn btn-primary' %>
      <div class="btn btn-default" data-dismiss='modal'>Cancel</div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#new_expenses_sub_category').syftValidator();
    });
</script>

app/views/expenses/sub_categories/create.js.erb
<% if @sub_category.errors.any? %>
popupMessage('<%= escape_javascript( errors_to_message_string(@sub_category.errors)).html_safe %>', 'alert-danger');
<% else %>
$("#expense_sub_category_id").append("<option value=<%= @sub_category.id %>> <%= @sub_category.name %></option>");
$('#expense_sub_category_id').trigger("chosen:updated");
$('#global-modal').modal('hide');
popupMessage('Sub-Category saved successfully.', 'alert-success');
<% end %>

app/views/expenses/sub_categories/edit.html.erb
<div class="row reset-padding">
  <div class="content-wrapper" id="rule-content">
    <div class="header-wrapper">
      <h4>
        Edit Product Sub-Category
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="text-centerx table-cell">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/sub_categories/index.html.erb
<div class="row reset-padding">
  <div class="content-wrapper" id="rule-content">
    <div class="header-wrapper">
      <div class="header-container clearfix">
        <h4 class="title-section">
          Expense Sub Category List
        </h4>

        <div class="action-section">
          <%= link_to new_expenses_category_sub_category_path(@category), class: 'btn btn-info' do %>
              New Sub Category
          <% end %>
        </div>
      </div>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper" id="provident-fund-rule-content">
      <% if @sub_categories.present? %>
        <div class="row actions-button">
          <div class="add-more-rule clearfix">
            <%= link_to new_expenses_category_sub_category_path(@category), class: 'btn btn-default pull-right' do %>
              <i class="fa fa-plus-circle"></i> Add Expense Sub-Category
            <% end %>
          </div>
        </div>
        <div class="row content-body">
          <h4>Category: <%= @category.name %></h4>
          <table class="table action-table beaccount-table tablesorter table-responsive table-hover table-striped">
            <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Description</th>
              <th></th>
            </tr>
            </thead>
            <tbody>
            <% @sub_categories.each do |sub_category| %>
              <tr>
                <td> #<%= sub_category.id %> </td>
                <td><%= sub_category.name %> </td>
                <td><%= sub_category.description %> </td>
                <td class="actions">
                  <%= link_to edit_expenses_category_sub_category_path(@category, sub_category), class: 'btn warning-color' do %>
                    <i class="fa fa-pencil-square-o"></i>
                  <% end %>
                  <%= link_to expenses_category_sub_category_path(@category, sub_category), class: 'btn danger-color', method: :delete, data: {confirm: 'Are you sure?'} do %>
                    <i class="fa fa-times"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      <% else %>
        <div class="text-center table-cell">
          <p>
            Current department don't have any Expense Sub-Category. <%#= link_to 'Learn more', '#', class: 'link' %>
            <!--<i class="fa fa-info-circle btn btn-info reset-border-radius" data-toggle='popover' data-placement='top' title="Provident Fund Account" data-content="Click on the create new one button to create provident fund account then it will show the account  list  "></i>-->
          </p>
          <%= link_to new_expenses_category_sub_category_path, class: 'btn btn-default reset-border-radius' do %>
            <i class="fa fa-plus-circle"></i> Add new one
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/expenses/sub_categories/new.html.erb
<div class="row reset-padding">
  <div class="content-wrapper" id="rule-content">
    <div class="header-wrapper">
      <h4>
        Add New Product Sub-Category
      </h4>
    </div>
    <div class="content-body-wrapper secondary-color full-content-wrapper">
      <div class="text-centerx table-cell">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/expenses/sub_categories/new.js.erb
$('#global-modal').modal({backdrop: 'static', keyboard: false});
$('#global-modal').modal('show').find('.modal-content').html("<%= escape_javascript(render 'form_modal').html_safe %>");