config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees, controllers: {
                           sessions: 'employees/sessions',
                           passwords: 'employees/passwords',
                           registrations: 'employees/registrations',
                           unlocks: 'employees/unlocks',
                           confirmations: 'employees/confirmations',
                           invitations: 'employees/invitations'
                       }

  as :employee do
    get 'login', to: 'devise/sessions#new', as: :user_login
    delete 'logout', to: 'devise/sessions#destroy', as: :user_logout
    get 'registration', to: 'devise/registrations#new', as: :company_registration
  end


  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/activities/:type', to: 'activities#changes'
      delete '/activities/remove', to: 'activities#remove'
      post '/activities/offline_changes', to: 'activities#offline_changes'
      resources :employees, only: [:index, :show]
      resources :departments, only: [:index]
      resources :members, only: [:index]
      namespace :pos do
        resources :suppliers, only: [:index]
        resources :customers, only: [:index]
        resources :products
      end
    end
  end


  post '/submit_contact', to: 'home#submit_contact', as: :submit_contact

  get '/terms-and-conditions', to: 'home#terms_and_conditions'
  get '/pricing', to: 'home#pricing'
  get '/take-a-tour', to: 'home#take_a_tour'
  get '/contact-us', to: 'home#contact_us', as: :contact_us
  get 'modules/employee', to: 'home#employee'
  get 'modules/attendance', to: 'home#attendance'
  get 'modules/bank', to: 'home#bank'

  resources :members

  # For employee resources
  resources :employees do
    get :attendances
    get :settings
    post :import, on: :collection
    get :profile
    get :download_templete, on: :collection
    post :add, on: :collection
    put :update_info, on: :member
    get :access_rights, on: :collection
    get :edit_password, on: :member
    patch :update_password, on: :collection
    patch :reset_password, on: :member
    put :activation, on: :member
    get :payroll_categories, on: :member
    get :increments, on: :member
    get :identity_attachment, on: :member
    get :card
  end

  get '/confirm_email', to: 'employees#confimed_email_error'
  resources :access_rights


  resources :departments do
    get :switch, on: :member
    get :all_settings, on: :member
    member do
      scope :settings do
        get :employee
        get :leave
        get :budget
        get :general
        get :attendance
        get :designation
      end
    end
  end

  resources :settings do
    get :confirm, on: :collection
    get :features, on: :collection
    get :billing, on: :collection
    post :payment_method, on: :collection
    post :company_feature, on: :collection
  end

  namespace :attendance do
    get :dashboard
    resources :attendances do
      get :history, on: :collection
      get :report, on: :collection
      get :employee_wise_report, on: :collection
      get :in, on: :collection
      get :out, on: :member
      get :stats, on: :collection
    end
    resources :day_offs do
      post :generate, on: :collection
    end
  end

  resources :designations, except: [:index]

  resources :companies do
    get :profile, on: :collection
    get :employee, on: :collection
    get :departments, on: :collection
  end

  namespace :bank do
    resources :accounts
  end

  namespace :expenses do
    resources :groups
    resources :categories do
      member do
        get :sub_cats
      end
      resources :sub_categories
    end
  end
  resources :expenses

  namespace :pos do

    namespace :customers do
      resources :categories
      resources :invoices do
        collection do
          get :close_invoice
        end
        member do
          get :history
        end
      end
      resources :invoice_items
      resources :payments
    end
    resources :customers do
      collection do
        post :process_invoice
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :suppliers do
      resources :purchases do
        member do
          get :receive
        end
        collection do
          get :history
        end
      end
      resources :purchase_items
      resources :payments
    end
    resources :suppliers do
      collection do
        post :process_purchase
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :products do
      resources :brands
      resources :models
      resources :categories do
        member do
          get :sub_categories
        end
      end
      resources :queue_codes do
        collection do
          get :print_barcode
          get :clear_all
        end
      end
      resources :sub_categories
      resources :price_tags
    end
    resources :products

    resources :stocks do
      collection do
        get :history
      end
    end
  end

  resources :changed_settings, only: [:new, :create, :edit, :update, :destroy]

  # You can have the root of your site routed with "root"
  root 'home#index'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  get '/*other', :to => 'errors#show', :code => 404
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_employee!
  skip_load_and_authorize_resource
  layout 'dashboard'

  def index
    @contact_us = ContactUs.new
    if current_employee.present?
      @company_modules = current_company.company_features
      @available_modules = @company_modules.present? ? Feature.where("id NOT IN (#{@company_modules.map(&:feature_id).join(',')})") : Feature.all
    else
      redirect_to user_login_path
    end
  end

  def submit_contact
    @contact_us = ContactUs.new(contact_params)
    if @contact_us.save
      ContactMailer.send_contact(@contact_us).deliver
      redirect_to root_path, notice: 'Your message has been successfully sent.'
    else
      render :index
    end
  end

  def email_subscribe
    @subscription = Subscription.find_by_email(params[:subscription][:email]) ? Subscription.new : Subscription.create(email: params[:subscription][:email])
    respond_to do |format|
      format.js
    end
  end

  def terms_and_conditions

  end

  def new

  end

  def community

  end

  def pricing

  end

  def take_a_tour

  end

  def email_template
    render layout: false
  end


  def feedback
    feedback = Feedback.new(feedback_params)
    @status = feedback.save
    respond_to do |format|
      format.js
      format.html {
        flash[:success] = 'Thank your kind feedback'
        redirect_to root_path
      }
    end
  end

  def employee
    @modules = Feature.all
  end

  def leave
    @modules = Feature.all
  end

  def attendance
    @modules = Feature.all
  end

  def provident_fund
    @modules = Feature.all
  end

  def expense
    @modules = Feature.all
  end

  def bank
    @modules = Feature.all
  end

  def contact_us
    @contact_us = ContactUs.new
  end

  private

  def subscribe_params
    params.require(:subscription).permit!

  end

  def contact_params
    params.require(:contact_us).permit!
  end

  def feedback_params
    params.require(:feedback).permit(:name, :email, :design, :response, :functional, :rate, :comments)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_app_dashboard.html.erb
<div class="site-container">
  <div class="header-wrapper">
    <h4>
      <span class="primary-color"> <%= current_company.name %> </span> Module Dashboard
    </h4>
  </div>

  <div class="content-body-wrapper secondary-color full-content-wrapper">
    <div class="text-centerx table-cell">
      <div id="app-dashboard-wrapper">
        <section class="company-module">
          <h2> <%= current_company.name %>'s Modules </h2>

          <div>
            <ul>
              <li>
                <%= link_to employees_path, class: 'somethings' do %>
                    <%= image_tag('module_settings/employee.png') %>
                    <p class="text-center">Employee</p>
                <% end %>
              </li>
              <% @company_modules.each do |app| %>
                  <li>
                    <%= link_to app.feature.url, class: 'somethings' do %>
                        <%= image_tag(app.feature.logo) %>
                        <p class="text-center"><%= app.feature.name %></p>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </div>
        </section>

        <% if @available_modules.present? %>
            <section class="available-module">
              <h2> Available Modules </h2>

              <div>
                <ul>
                  <% @available_modules.each do |app| %>
                      <li>
                        <%= link_to settings_path, class: 'somethings' do %>
                            <%= image_tag(app.logo) %>
                            <p class="text-center"><%= app.name %></p>
                        <% end %>
                      </li>
                  <% end %>
                </ul>
              </div>
            </section>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/home/_feature_modules.html.erb
<div class="col-sm-3">
  <div class="module-list ">
    <h2 class="mb20 mt25 fz20"> Modules </h2>
    <ul class="clearfix common-ul-style module-features-list">
      <li>
        <!--<a href="">-->
        <!--<i class="fa fa-check text-success"></i>-->
        <!--<p> Employee </p>-->
        <!--</a>-->
        <%= link_to modules_employee_path, class:'fa fa-check text-success p15' do %>
            Employee
        <% end %>
      </li>
        <% modules.each do |feature|  %>
           <li>
             <%= link_to "/modules/#{feature.name.gsub(' ', '_').downcase}", class:'fa fa-check text-success p15' do %>
                 <%= feature.name %>
             <% end %>
           </li>
        <% end %>

    </ul>
  </div>
</div>

<%# if feature.name == 'Leave'%>
<%# if feature.name == 'Payroll'%>
<%# if feature.name == 'Expense'%>
<%# if feature.name == 'Provident Fund'%>

app/views/home/attendance.html.erb
<div class="mt75">
  <div class="container">
    <div class="col-sm-12">
      <div class="col-sm-9">
        <div class="module-detail">
          <h2 class="page-header"> Attendance Management </h2>
          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/attendance/attendance_dashboard.png' %>" class="preview-attachment">
                <%= image_tag 'modules/attendance/attendance_dashboard.png', class: 'img-responsive' %>
              </a>
            </div>
            <div class="col-sm-6", style="text-align: justify">

              The attendance is an activity module for tracking time spent by Employees (or other users) in a Company
              or in a related group of Institution. By clicking the in button on the attendance dashboard
              or the floating button at the right side of the website will start counting time. In time and
              working hours can be set from the department settings. It also calculates wheather the employee
              is early or late to work.
            </div>
          </div>

          <div class="row mt20 mb80", style="text-align: justify">
            <div class="col-sm-6">
              this page is for checking the status of employee attendance of current day. In time , out time,
              duration all of those can be seen from this page. Clicking the pie chart like button after every
              employee name will show that employee's attendance statistic of the month.
            </div>
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/attendance/employee_attendance.png' %>" class="preview-attachment">
                <%= image_tag 'modules/attendance/employee_attendance.png', class: 'img-responsive' %>
              </a>
            </div>
          </div>

          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/attendance/attendence_history.png' %>" class="preview-attachment">
                <%= image_tag 'modules/attendance/attendence_history.png', class: 'img-responsive' %>
              </a>
            </div>
            <div class="col-sm-6", style="text-align: justify">
              HR might want to see attendance history of employees from and to a selected date.
              This feature does that work easier for the HR to keep track of attendances.
            </div>
          </div>
          <div class="row mt20 mb80", style="text-align: justify">
            <div class="col-sm-6">
              This page is for the personal attendance statistic of employees. This report has everything that
              anyone can wist for when it comes in terms of attendance. Holiday, holiday reson,
              leaves, in time, out time, worked duration, late and overtime,  it has all of these.
            </div>
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/attendance/attendance_breakdown.png' %>" class="preview-attachment">
                <%= image_tag 'modules/attendance/attendance_breakdown.png', class: 'img-responsive' %>
              </a>
            </div>
          </div>
          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/attendance/monthly_attendance_report.png' %>" class="preview-attachment">
                <%= image_tag 'modules/attendance/monthly_attendance_report.png', class: 'img-responsive' %>
              </a>
            </div>
            <div class="col-sm-6", style="text-align: justify">
              It's the monthly attendance report of every employee of the organization.
              It shows day to day attendace that can save HR's time and pain much much more.
              This report makes attendance management mush easier.
            </div>
          </div>


        </div>
      </div>

      <%= render 'home/feature_modules', modules:@modules %>

    </div>
  </div>


</div>

<script type="text/javascript">
    $(function(){
        $('.preview-attachment').attachmentPreview();
    });
</script>

app/views/home/bank.html.erb
<div class="mt75">
  <div class="container">
    <div class="col-sm-12">
      <div class="col-sm-9">
        <div class="module-detail">
          <h2 class="page-header"> Bank </h2>
          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/bank/bank_account_list.png' %>" class="preview-attachment">
                <%= image_tag 'modules/bank/bank_account_list.png', class: 'img-responsive' %>
              </a>
            </div>
            <div class="col-sm-6", style="text-align: justify">
              Keep track of your bank accounts with this module of ours. How much your account have,
              and also edit feature which can edit your credentials.
              There are many more feature to come in this module.

            </div>
          </div>

          <div class="row mt20 mb80", style="text-align: justify">
            <div class="col-sm-6">
              Bank account can be created by filling up some forms. Simple, isn't it!

            </div>
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/bank/create_bank_account.png' %>" class="preview-attachment">
                <%= image_tag 'modules/bank/create_bank_account.png', class: 'img-responsive' %>
              </a>
            </div>
          </div>


        </div>
      </div>

      <%= render 'home/feature_modules', modules:@modules %>

    </div>
  </div>


</div>
<script type="text/javascript">
    $(function(){
        $('.preview-attachment').attachmentPreview();
    });
</script>

app/views/home/contact_us.html.erb
<!-- Contact Us Section Design -->
<div class="contact-us-wrapper <%= 'full-height' if(controller_name == 'home' && action_name == 'contact_us')%> " id="contact_us">
  <div class="contact-us-bg-opacity">
    <div class="contact-us-container container mt45 ">
      <div class="contact-us-row row">
        <h2 class="title title-h2 text-center">Send us a quote</h2>

        <div class="form-wrapper clearfix">
          <!--send us a quote section-->
          <%= form_for(@contact_us, url: submit_contact_path, html: {class: 'form-vertical', role: 'form', id: 'send-us-quote-form'}) do |f| %>
              <div class="form-name-item-row clearfix">
                <div class="form-name-item-container col-md-4">
                  <div class="form-name-item-group form-group">
                    <!-- <input name='your-name' type="text" class="custom-form-control custom-placeholder" placeholder="Name *" onfocus="this.placeholder=''" onblur="this.placeholder='Name *'"> -->
                    <%= f.text_field :name, class: "custom-form-control custom-placeholder", placeholder: 'Name *', onfocus: "this.placeholder=''", onblur: "this.placeholder='Name *'", required: true %>
                  </div>
                </div>

                <div class="form-name-item-container col-md-4">
                  <div class="form-name-item-group form-group">
                    <!--  <input name='your-email' type="email" class="custom-form-control custom-placeholder" placeholder="Email *" onfocus="this.placeholder=''" onblur="this.placeholder='Email *'"> -->
                    <%= f.email_field :email, class: "custom-form-control custom-placeholder", placeholder: 'Email *', onfocus: "this.placeholder=''", onblur: "this.placeholder='Email *'", required: true %>
                  </div>
                </div>

                <div class="form-name-item-container col-md-4">
                  <div class="form-name-item-group form-group">
                    <!--   <input name="your-subject" type="text" class="custom-form-control custom-placeholder" placeholder="Subject" onfocus="this.placeholder=''" onblur="this.placeholder='Subject'"> -->
                    <%= f.text_field :subject, class: "custom-form-control custom-placeholder", onfocus: "this.placeholder=''", onblur: "this.placeholder='Subject'", placeholder: 'Subject' %>
                  </div>
                </div>

                <div class="form-name-item-container col-md-12">
                  <div class="form-name-item-group form-group">
                    <!--   <textarea name="your-message" class="custom-form-control custom-placeholder" rows="5" placeholder="Message" onfocus="this.placeholder=''" onblur="this.placeholder='Message'"></textarea> -->
                    <%= f.text_area :message, class: "custom-form-control custom-placeholder", placeholder: 'Message', onfocus: "this.placeholder=''", onblur: "this.placeholder='Message'", rows: 5 %>
                  </div>
                </div>
              </div>

              <script type="text/javascript">
                  var onloadCallback = function () {
                      grecaptcha.render('g_recaptcha', {
                          'sitekey': '6LcZ8xEUAAAAAJxRTPhrnRslryX_mbXYjkoFTOf1'
                      });
                  };
              </script>
              <div id="g_recaptcha" class="pl14"></div>
              <div class="col-xs-12 text-right">
                <%= f.submit 'SUBMIT', class: 'custom-button', id: 'send-us-quote-submit-btn' %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/home/employee.html.erb
<div class="mt75">
  <div class="container">
    <div class="col-sm-12">
      <div class="col-sm-9">

        <div class="module-detail">
          <h2 class="header-page"> Employee Management </h2>

          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/employee/employee_list.png' %>" class="preview-attachment">
                <%= image_tag 'modules/employee/employee_list.png', class: 'img-responsive' %>
              </a>
            </div>

            <div class="col-sm-6 text-justify">
              The Employee Module contains necessary forms and reports to keep track all of your
              Employee Data, including Advances, Advances History, Certificates, Right Access etc.
              This module also keep track of Active and Deactivated (previous employee not now present) Employees.
              If your company has a huge number of employees those are to be difficult to include, don't worry Bequent
              solved this types of problem very easily, click 'Upload Employees' and download template fill up your
              employees necessary fields then choose that file and click just Import button.
              <i class="warning-color"> N.B. Please provide your employees required and right information. </i>
              Search Employee by Name, Employee ID, Email, Phone etc and you can download your Employee List on Export to.
            </div>
          </div>

          <div class="row mt20 mb80">
            <div class="col-sm-6 text-justify">
              If employee needs to Advance, Company starts calculating how that can be done and it surely is a nightmare
              for the Company to record all this data manually. In Bequent give you a user friendly solution just create
              a 'New Advance' fill up your field and you can return Advance by click on 'Advance Return' option that all.
            </div>
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/employee/employee_advance.png' %>" class="preview-attachment">
                <%= image_tag 'modules/employee/employee_advance.png', class: 'img-responsive' %>
              </a>
            </div>
          </div>

          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/employee/advance_history.png' %>" class="preview-attachment">
                <%= image_tag 'modules/employee/advance_history.png', class: 'img-responsive' %>
              </a>
            </div>
            <div class="col-sm-6 text-justify">
              Advance History provides all of data of Employees Advance such as 'Advance given', 'Advance return',
              'Balance'and you can export history report with doc and pdf format etc.
            </div>
          </div>

          <div class="row mt20 mb80">
            <div class="col-sm-6 text-justify">
              Bequent has a best user friendly Employee Profile which are provides a lot of information of employee
              such as personal info, Attendance, Leave and Settings option for change your password.
            </div>
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/employee/employee_dashboard.png' %>" class="preview-attachment">
                <%= image_tag 'modules/employee/employee_dashboard.png', class: 'img-responsive' %>
              </a>
            </div>
          </div>

          <div class="row mt20 mb80">
            <div class="col-sm-6">
              <a href="javascript:void(0)" data-content="<%= image_path 'modules/employee/access_right.png' %>" class="preview-attachment">
                <%= image_tag 'modules/employee/access_right.png', class: 'img-responsive' %>
              </a>
            </div>
            <div class="col-sm-6 text-justify">
              Everyone has assign different task in Company under various department with many different types of
              rules and regulations. All are not able to Access in all features so admin can easily modify their
              'Access Rights' by Employee module Access Rights option.
              If you need a HR, create employee with required information and give the HR proper Access Rights fields where you want
              thats all.
            </div>
          </div>
        </div>

      </div>

      <%= render 'home/feature_modules', modules: @modules %>

    </div>
  </div>


</div>

<script type="text/javascript">
    $(function () {
        $('.preview-attachment').attachmentPreview();
    });
</script>

app/views/home/index.html.erb
<%= render 'home/app_dashboard' %>

app/views/home/take_a_tour.html.erb
<div class="take-a-tour site-container">

  <div class="tour-main-wrap">
    <!-- Header -->
    <div class="tour-header-wrap">
      <div class="tour-header-container">
        <h1><span class="guest-color">Be</span>quent</h1>
        <!--<p>Business process automation with <a href="#"><span class="guest-color">Be</span>quent</a></p>-->
        <p style="color: tomato; font-weight: bold">
          your feedback makes
          <%= link_to root_path do %>
              <span class="guest-color">Be</span>quent
          <% end %> more enrich
        </p>
      </div>
    </div>

    <!-- Wrapper -->
    <div class="tour-body-wrap">

      <!-- Items -->
      <div class="products-wrap">

        <div class="product-wrap ">
          <div class="product-item reset-border-radius">
            <iframe width="100%" height="315" src="https://www.youtube.com/embed/eQwXqXX8imc" frameborder="0" allowfullscreen></iframe>
          </div>
          <p>
            Create a new employee with details information such as employee Personal information,
            Account information, Contact information, Emergency contact etc. If your company has a huge number
            of employees those are to be difficult to include, don't worry Bequent solved this types of problem
            very easily.
            <br><br>
            <%= link_to modules_employee_path, class: 'read-more mt10', target: '_blank' do %>
                Read More...
            <% end %>
          </p>
        </div>
        <div class="product-wrap">
          <div class="product-item reset-border-radius">
            <iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/bXltGhj-gho" frameborder="0" allowfullscreen></iframe>
          </div>
          <p>
            For your company you can create your leave application and easily customize your leave.
            Bequent makes it too much suitable and user friendly with a huge leave futures such as
            Leave application, Employee status, Report, Leave summary and Leave calender etc.
            <br><br>
            <%= link_to modules_leave_path, class: 'read-more mt10', target: '_blank' do %>
                Read More...
            <% end %>
          </p>
        </div>
        <div class="product-wrap">
          <div class="product-item reset-border-radius">
            <iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/3tHcZHp_qic" frameborder="0" allowfullscreen></iframe>
          </div>
          <p>
            Attendance module makes more enrich the Bequent. There are three types attendance added to count
            working hours and leave which are Punched card, Finger punched and simply In/Out button with login
            options. Offline attendance is ready for your company to give you a comfort life.
            Let's drink a mean cup of coffee and enjoy it.
            <br><br>
            <%= link_to modules_attendance_path, class: 'read-more mt10', target: '_blank' do %>
                Read More...
            <% end %>
          </p>
        </div>
        <div class="product-wrap">
          <div class="product-item reset-border-radius">
          </div>
          <p>
            All types of salary issue are being merged in payroll module and this management systems has
            lots of standard reports like department wise gross salary, total deduction, net salary, monthly
            employee salary, company wise salary etc.
            <br><br>
            <%= link_to modules_payroll_path, class: 'read-more mt10', target: '_blank' do %>
                Read More...
            <% end %>
          </p>
        </div>

        <div class="product-wrap">
          <div class="product-item reset-border-radius">
            <iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/NOVIncvj6dg" frameborder="0" allowfullscreen></iframe>
          </div>
          <p>
            Provident fund module designed to process and provide all information starting form recruitment till final
            settlement at one click. At first in the dashboard we represents contribution such as total company
            contribution
            and total employee contribution in graphically which are easy to understand. You can create your rules as
            you want.
            Another more rich features are Provident fund contribution, Investment, Loan and Cash Statement.
            <br><br>
            <%= link_to modules_provident_fund_path, class: 'read-more mt10', target: '_blank' do %>
                Read More...
            <% end %>
          </p>
        </div>

        <div class="product-wrap">
          <div class="product-item reset-border-radius">
            <iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/mrBHZIu_Ur4" frameborder="0" allowfullscreen></iframe>
          </div>
          <p>
            In expense module feature, you can implement an approval process that will allow you to
            monitor costs before your employees actually incur expenses. At dashboard you can see Monthly
            expenses, Top expenses, Total expense, Life expense. You can compare Monthly expenses. Also more
            rich features are ready to here give you 100% flexibility such as Monthly report, Yearly report and
            Category wise report.
            <br><br>
            <%= link_to modules_expense_path, class: 'read-more mt10', target: '_blank' do %>
                Read More...
            <% end %>

          </p>
        </div>

      </div>

    </div>
  </div>


</div>