config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :employees, controllers: {
                           sessions: 'employees/sessions',
                           passwords: 'employees/passwords',
                           registrations: 'employees/registrations',
                           unlocks: 'employees/unlocks',
                           confirmations: 'employees/confirmations',
                           invitations: 'employees/invitations'
                       }

  as :employee do
    get 'login', to: 'devise/sessions#new', as: :user_login
    delete 'logout', to: 'devise/sessions#destroy', as: :user_logout
    get 'registration', to: 'devise/registrations#new', as: :company_registration
  end


  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get '/activities/:type', to: 'activities#changes'
      delete '/activities/remove', to: 'activities#remove'
      post '/activities/offline_changes', to: 'activities#offline_changes'
      resources :employees, only: [:index, :show]
      resources :departments, only: [:index]
      resources :members, only: [:index]
      namespace :pos do
        resources :suppliers, only: [:index]
        resources :customers, only: [:index]
        resources :products
      end
    end
  end


  post '/submit_contact', to: 'home#submit_contact', as: :submit_contact

  get '/terms-and-conditions', to: 'home#terms_and_conditions'
  get '/pricing', to: 'home#pricing'
  get '/take-a-tour', to: 'home#take_a_tour'
  get '/contact-us', to: 'home#contact_us', as: :contact_us
  get 'modules/employee', to: 'home#employee'
  get 'modules/attendance', to: 'home#attendance'
  get 'modules/bank', to: 'home#bank'

  resources :members

  # For employee resources
  resources :employees do
    get :attendances
    get :settings
    post :import, on: :collection
    get :profile
    get :download_templete, on: :collection
    post :add, on: :collection
    put :update_info, on: :member
    get :access_rights, on: :collection
    get :edit_password, on: :member
    patch :update_password, on: :collection
    patch :reset_password, on: :member
    put :activation, on: :member
    get :payroll_categories, on: :member
    get :increments, on: :member
    get :identity_attachment, on: :member
    get :card
  end

  get '/confirm_email', to: 'employees#confimed_email_error'
  resources :access_rights


  resources :departments do
    get :switch, on: :member
    get :all_settings, on: :member
    member do
      scope :settings do
        get :employee
        get :leave
        get :budget
        get :general
        get :attendance
        get :designation
      end
    end
  end

  resources :settings do
    get :confirm, on: :collection
    get :features, on: :collection
    get :billing, on: :collection
    post :payment_method, on: :collection
    post :company_feature, on: :collection
  end

  namespace :attendance do
    get :dashboard
    resources :attendances do
      get :history, on: :collection
      get :report, on: :collection
      get :employee_wise_report, on: :collection
      get :in, on: :collection
      get :out, on: :member
      get :stats, on: :collection
    end
    resources :day_offs do
      post :generate, on: :collection
    end
  end

  resources :designations, except: [:index]

  resources :companies do
    get :profile, on: :collection
    get :employee, on: :collection
    get :departments, on: :collection
  end

  namespace :bank do
    resources :accounts
  end

  namespace :expenses do
    resources :groups
    resources :categories do
      member do
        get :sub_cats
      end
      resources :sub_categories
    end
  end
  resources :expenses

  namespace :pos do

    namespace :customers do
      resources :categories
      resources :invoices do
        collection do
          get :close_invoice
        end
        member do
          get :history
        end
      end
      resources :invoice_items
      resources :payments
    end
    resources :customers do
      collection do
        post :process_invoice
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :suppliers do
      resources :purchases do
        member do
          get :receive
        end
        collection do
          get :history
        end
      end
      resources :purchase_items
      resources :payments
    end
    resources :suppliers do
      collection do
        post :process_purchase
      end
      member do
        get :history
        get :print_voucher
      end
    end

    namespace :products do
      resources :brands
      resources :models
      resources :categories do
        member do
          get :sub_categories
        end
      end
      resources :queue_codes do
        collection do
          get :print_barcode
          get :clear_all
        end
      end
      resources :sub_categories
      resources :price_tags
    end
    resources :products

    resources :stocks do
      collection do
        get :history
      end
    end
  end

  resources :changed_settings, only: [:new, :create, :edit, :update, :destroy]

  # You can have the root of your site routed with "root"
  root 'home#index'

  %w( 404 422 500 503 ).each do |code|
    get code, :to => 'errors#show', :code => code
  end

  get '/*other', :to => 'errors#show', :code => 404
end

app/controllers/api/v1/departments_controller.rb
class Api::V1::DepartmentsController < Api::V1::V1Base

  def index
    department = Department.find(params[:department_id])
    @departments = department.company.departments
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :current_ability
  before_action :set_department, only: [:edit, :update, :destroy, :show, :employee, :leave, :attendance, :general, :budget, :designation, :all_settings]

  def index
    @departments = current_department.company.departments
    respond_to do |format|
      format.js
      format.xls
      format.pdf do
        render pdf: 'report', layout: 'pdf', template: 'departments/department_list_pdf.html.erb', encoding: 'utf-8'
      end
      format.docx do
        render docx: 'report', template: 'departments/index.docx.erb', encoding: 'utf-8'
      end
    end
  end

  def new
    @department = Department.new(company_id: current_company.id)
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def edit
    respond_to do |format|
      format.js
    end
  end

  def create
    @department = current_company.departments.build(department_params)
    respond_to do |format|
      if @department.save
        format.html { redirect_to all_settings_department_path(@department), success: 'Department was successfully created' }
        format.json { render json: @department, status: :ok }
        format.js
      else
        format.html { render :new, danger: "Department couldn't be created" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def show
    @department.get_settings(Date.today)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def employee
    @employees = @department.employees.order(id: :desc)
    @view = 'employee_list'
    respond_to do |format|
      format.html { render :show }
      format.js { render :show }
      format.xls do
        render xls: 'Employees', layout: 'excel', template: 'employees/employee_list_xls_doc.html.erb', encoding: 'utf-8'
      end
      format.pdf do
        render pdf: 'Employees', layout: 'pdf', template: 'employees/employee_list_pdf.html.erb', encoding: 'utf-8'
      end
      format.docx do
        render docx: 'Employees', layout: 'document', template: 'employees/employee_list_xls_doc.html.erb', encoding: 'utf-8'
      end
    end
  end

  def general
    @setting = @department.setting
    @changed_settings = @department.changed_settings
    @view = 'settings/general'
    render :show
  end

  def attendance
    @events = @department.events
    @view = 'settings/attendance'
    render :show
  end

  def designation
    @designations = @department.designations
    @view = 'designation_list'
    respond_to do |format|
      format.html { render :show }
      format.js { render :show }
      format.xls do
        render xls: 'Designations', layout: 'excel', template: 'departments/designations_xls_docx.html.erb', encoding: 'utf-8'
      end
      format.pdf do
        render pdf: 'Designations', layout: 'pdf', template: 'departments/designations_pdf.html.erb', encoding: 'utf-8'
      end
      format.docx do
        render docx: 'Designations', layout: 'document', template: 'departments/designations_xls_docx.html.erb', encoding: 'utf-8'
      end
    end
  end

  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: "Department was successfully created" }
        format.json { render :show, status: :ok, location: @department }
        format.js
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    respond_to do |format|
      if @department == current_employee.department
        format.html { redirect_to profile_companies_path, notice: 'You are in the department So you have to switch yourself to another department' }
        format.json { head :no_content }
        format.js
      else
        @department.destroy!
        format.html { redirect_to profile_companies_path, notice: 'Successfully deleted' }
        format.json { head :no_content }
        format.js
      end
    end
  end

  def switch
    @department = Department.friendly.find(params[:id])
    session[:department_id] = @department.id if @department.present?
    if Rails.application.routes.recognize_path(request.referrer)[:controller] == 'departments' && (Department::SWITCH_ACTIONS.values.include? Rails.application.routes.recognize_path(request.referrer)[:action])
      redirect_to @department.action_path(Rails.application.routes.recognize_path(request.referrer)[:action])
    else
      redirect_to request.referer
    end
  end

  def all_settings
    @setting = @department.setting
    @designations = @department.designations
    @leave_categories = @department.leave_categories
  end

  private

  def set_department
    begin
      @department = Department.where(company_id: current_company.id).friendly.find(params[:id]) #.departments.friendly.find(params[:id])
    rescue
      @department = current_department
    end
  end

  def department_params
    params.require(:department).permit!
  end

end

app/helpers/api/v1/departments_helper.rb
module Api::V1::DepartmentsHelper
end

app/views/departments/all_settings_partials/_designations.html.erb
<div class="step-content-wrapper">
  <h2>Add Employee Designations</h2>

  <!-- Add to button start-->
  <div class="clearfix">
    <div class="pull-right">
      <div class="btn-group mr10 reset-padding">
        <%= link_to new_designation_path(department: @department), remote: true, class: 'btn btn-default reset-border-radius' do %>

            <i class="fa fa-plus"></i> Add New
        <% end %>
      </div>
    </div>
  </div>
  <!-- Add to button close-->

  <!-- Designation table start-->
  <div class="table-warapper mt10">
    <div class="table-warapper-body">
      <table class="table action-table tablesorter beaccount-table designation-list-table table-responsive table-hover table-striped">
        <thead>
        <tr>
          <th>Name</th>
          <th>Responsibilities</th>
          <th>Status</th>
          <th></th>
        </tr>
        </thead>
        <tbody id="designation-list">
        <% @designations.each do |designation| %>
            <%= render 'departments/templates/add_designation', designation: designation %>
        <% end %>
        </tbody>
      </table>
      <div id="pager1">
        <%= render 'shared/pagination' if @designations.size > 10 %>
      </div>
      <div class="no-data-found">
        <% unless @designations.present? %>
            <%= render 'shared/no_data_found', message: 'No designation found' %>
        <% end %>
      </div>
    </div>
  </div>
  <!-- Designation table close-->

</div>

app/views/departments/all_settings_partials/_general.html.erb
<div class="step-content-wrapper">
  <h2>General Settings</h2>
  <%= form_for @setting, remote: true do |f| %>
      <div class="row">
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label :open_time %>
            <%= f.text_field :open_time, class: 'form-control reset-border-radius', id: "department_open_time", value: f.object.open_time.present? ? f.object.open_time.strftime("%I:%M %p") : '' %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label :working_hours %>
            <%= f.number_field :working_hours, class: 'form-control reset-border-radius' %>
          </div>
        </div>
        <!--<div class="col-sm-6">-->
        <!--<div class="form-group">-->
        <!--<%#= f.label :close_time %>-->
        <!--<%#= f.text_field :close_time, class: 'form-control reset-border-radius', id: "department_close_time", value: f.object.close_time.present? ? f.object.close_time.strftime("%I:%M %p") : '' %>-->
        <!--</div>-->
        <!--</div>-->
      </div>

      <div class="row">
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label :time_zone %>
            <%= f.time_zone_select :time_zone, nil, {include_blank: true}, {class: 'form-control reset-border-radius'} %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="form-group">
            <%= f.label :currency %>
            <%= f.currency_select :currency, nil, {include_blank: true}, {class: 'form-control reset-border-radius'} %>
          </div>
        </div>
      </div>

      <%= hidden_field_tag :step_wise, 'yes' %>

      <div class="clearfix">
        <div class="pull-right">
          <%= f.submit 'Save Changes', class: 'primary-color-bg-with-hover' %>
        </div>
      </div>
  <% end %>
</div>

<script type="text/javascript">
    $(function () {
        $('#department_open_time').datetimepicker({
            format: 'LT'
        });
    });
</script>

app/views/departments/all_settings_partials/_leave.html.erb
<div class="step-content-wrapper">
  <h2>Add Leave Categories</h2>
  <div class="p10">
    <!-- Add leave category starts-->

    <div class="row mb10">
      <div class="col-md-6">
        <h4 class="mb0">Leave Categories</h4>
      </div>
      <div class="col-md-6 clearfix">
        <%= link_to new_leave_category_path(department_id: @department.id, year: params[:date].present? ? params[:date][:year] : Date.today.year , all_settings: true), remote: true, class: 'btn btn-default pull-right reset-border-radius' do %>
            <i class="fa fa-plus"> </i> New Leave Category
        <% end %>
      </div>
    </div>

    <!-- Add leave category ends-->

    <!-- Leave Category table starts-->

    <div class="leave-list2">
      <table class='table beaccount-table table-striped table-hover'>
        <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th></th>
        </tr>
        </thead>
        <tbody>

        <% @leave_categories.each do |leave_category| %>
            <%= render 'departments/all_settings_partials/leave_item', leave_category: leave_category %>
        <% end %>
        </tbody>
      </table>
      <%= render 'shared/pagination' if @leave_categories.size > 10 %>
      <div class="no-data-found">
        <% unless @leave_categories.present? %>
            <%= render 'shared/no_data_found', message: 'No leave category' %>
        <% end %>
      </div>
    </div>

    <!-- Leave Category table ends-->
  </div>
</div>

app/views/departments/all_settings_partials/_leave_item.html.erb
<tr id="leave-category-<%= leave_category.id %>">

  <td>
    <%= leave_category.name %>
  </td>

  <td>
    <%= truncate(leave_category.description, length: 30) %>
  </td>

  <td class="actions">
    <%= link_to leave_category_path(leave_category), remote: true, class: 'btn info-color' do %>
        <i class="fa fa-eye"></i>
    <% end %>
    <%= link_to edit_leave_category_path(leave_category), remote: true, class: 'btn warning-color' do %>
        <i class="fa fa-pencil-square-o"></i>
    <% end %>
  </td>

</tr>

app/views/departments/all_settings_partials/_payroll.html.erb
<div class="step-content-wrapper">
  <h2>Add Payroll Categories</h2>

  <div class="actions-button">
    <div class="clearfix">
      <div class="pull-right">
        <div class="btn-group" id="new-payroll-category-button">
          <%= link_to '#', remote: true, class:'btn btn-default reset-border-radius' do%>
              <i class="fa fa-plus"></i> Add New
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div id="categories">
    <%#= render 'payroll/categories/categories_table' %>
  </div>
</div>

app/views/departments/all_settings_partials/_weekend.html.erb
<div class="step-content-wrapper">
  <h2>Add Weekend</h2>
  <div class="m10">
    <div class="mb20">
      <%= form_tag generate_attendance_day_offs_path(department: @department), remote: true, id: 'dayoff-generator-form'  do %>

          <table class="table weekend-table">
            <tbody>
            <tr>
              <td> <%= label_tag :weekend, 'Select Weekend' %> </td>
              <td>
                <%= select_tag :weekend, options_for_select(7.times.collect { |day| Date::DAYNAMES[day] }), {prompt: 'Select weekend for current year', class: 'form-control'} %>
              </td>
              <td>
                <input type="submit" class="primary-color-bg-with-hover" value="Generate Weekend List" name="commit" data-toggle='popover' data-placement='bottom' data-content="This option for generating weekend for current year. You have to generate weekend in every year." id="leaveSubmit">
              </td>
            </tr>
            </tbody>
          </table>
      <% end %>
    </div>
  </div>
</div>